Fix Error when cleaning up reservations
return_by_id() changes the _reservations[ctx] set. Since that set is
beeing iterated over, it throws this error:

        RuntimeError: Set changed size during iteration

Fixed by iterating over a copy.