http: Fix no_proxy env variable parsing
Don't parse no_proxy as a URL, because it's just a pattern. This fixes
an error, when no_proxy is set:

    ValueError: Unknown scheme ""