Replace pydantic with dataclasses
pydantic doesn't work with Python 3.14:

      File "/home/runner/work/not-my-board/not-my-board/not_my_board/_hub.py", line 268, in register_place
        if place.name in self._place_names:
           ^^^^^^^^^^
    AttributeError: 'Place' object has no attribute 'name'

Use this as an excuse to finally get rid of that dependency and replace
it with dataclasses and custom validation logic. Some other reasons:
- the dependency is huge and barely used
- we're on version 1 while version 2 is out and version 3 is announced
- version 2 is written in Rust, which is overkill for our use-case