openssl: Add keyUsage to Hub CA
keyUsage is enforced with Python 3.13:

    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: CA cert does not include key usage extension (_ssl.c:1018)